openapi: 3.0.0
info:
  title: Boiler-Plate
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/v1/auth/register:
    post:
      tags:
        - General
      summary: register-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: nickelfox
                residence: noida
                password: nickelfox
                email: nickelfox@gmail.com
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
